# Generated by Django 2.0 on 2020-01-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titel',
            new_name='title',
        ),
    ]
