# Generated by Django 2.0 on 2020-01-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200104_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='last_uptaded_time',
            new_name='last_uptadaed_time',
        ),
    ]
