# Generated by Django 2.0 on 2020-01-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200104_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-last_uptadaed_time']},
        ),
    ]
